//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granda.HSMS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Granda.HSMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized Device Id 的本地化字符串。
        /// </summary>
        internal static string S9F1 {
            get {
                return ResourceManager.GetString("S9F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Too Long 的本地化字符串。
        /// </summary>
        internal static string S9F11 {
            get {
                return ResourceManager.GetString("S9F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversation Timeout 的本地化字符串。
        /// </summary>
        internal static string S9F13 {
            get {
                return ResourceManager.GetString("S9F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized Stream Type 的本地化字符串。
        /// </summary>
        internal static string S9F3 {
            get {
                return ResourceManager.GetString("S9F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized Function Type 的本地化字符串。
        /// </summary>
        internal static string S9F5 {
            get {
                return ResourceManager.GetString("S9F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal Data 的本地化字符串。
        /// </summary>
        internal static string S9F7 {
            get {
                return ResourceManager.GetString("S9F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction Timer Timeout 的本地化字符串。
        /// </summary>
        internal static string S9F9 {
            get {
                return ResourceManager.GetString("S9F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S9Fy message reply. 的本地化字符串。
        /// </summary>
        internal static string S9Fy {
            get {
                return ResourceManager.GetString("S9Fy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream number must be less than 127 的本地化字符串。
        /// </summary>
        internal static string SecsMessageStreamNumberMustLessThan127 {
            get {
                return ResourceManager.GetString("SecsMessageStreamNumberMustLessThan127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment is not online mode 的本地化字符串。
        /// </summary>
        internal static string SxF0 {
            get {
                return ResourceManager.GetString("SxF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T3 Timeout! 的本地化字符串。
        /// </summary>
        internal static string T3Timeout {
            get {
                return ResourceManager.GetString("T3Timeout", resourceCulture);
            }
        }
    }
}
